### ISSUE TITLE
4.1.1 build 2 removes cxx11 symbols

### ISSUE THREAD

**Issue by saraedum** [conda-forge/givaro-feedstock#13]
on linux-64, the latest build removed the symbol `_ZNK6Givaro7IntegercvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEB5cxx11Ev` from the library. It's my understanding that this is a compatibility symbol for an older ABI.

I think we could rebuild with `-fabi-version=2` on GCC to get this symbol back. Or just mark the latest linux build as broken. Any minor upgrade to givaro is going to fix this problem due to the exact pinning.

**Comment by saraedum** [comment]
See http://gcc.1065356.n8.nabble.com/Trying-to-understand-the-fabi-version-n-and-fabi-compat-version-n-options-td1643692.html for an imho helpful discussion.

**Comment by isuruf** [comment]
Let's mark the build 2 as broken. https://github.com/conda-forge/admin-requests
